// Images are read as they are displayed: EXIF orientation applied, transparency
// composited onto white. Inputs that are already upright and opaque take the
// same path as before, byte for byte.
//
// The fixtures are shared by all four bindings and generated by
// scripts/generate_input_fixtures.py; its docstring describes each one.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const { openImage, normalizePageForSegmentation } = require('../src/monocr');
const { fakeSession, StubOCR, BUNDLED_CHARSET } = require('./helpers');

const REPO = path.join(__dirname, '..', '..');
const FIXTURES = path.join(REPO, 'data', 'fixtures', 'input');
const SAMPLES = fs.readdirSync(path.join(REPO, 'data', 'images')).sort()
    .map((f) => path.join(REPO, 'data', 'images', f));

const ORIENTED = [1, 2, 3, 4, 5, 6, 7, 8].map((n) => `orient-${n}.jpg`)
    .concat(['orient-6-be.jpg', 'orient-6.png']);

// JPEG rounding on these block-aligned quality-100 fixtures is a few levels at
// most; a wrong orientation differs by 36 or more on average, or changes shape.
const TOLERANCE = 8;

async function grey(pipeline) {
    return pipeline.grayscale().raw().toBuffer({ resolveWithObject: true });
}

/** The page the segmenter is handed, decoded back to grey pixels. */
async function loadedPage(file) {
    return grey(sharp(await normalizePageForSegmentation(file)));
}

function maxDiff(a, b) {
    let m = 0;
    for (let i = 0; i < a.length; i++) m = Math.max(m, Math.abs(a[i] - b[i]));
    return m;
}

async function stubOcr() {
    const ocr = new StubOCR(fakeSession(), BUNDLED_CHARSET);
    await ocr.init();
    return ocr;
}

for (const name of ORIENTED) {
    test(`${name} loads upright`, async () => {
        const want = await grey(sharp(path.join(FIXTURES, 'upright.png')));
        const got = await loadedPage(path.join(FIXTURES, name));
        assert.equal(got.info.width, want.info.width);
        assert.equal(got.info.height, want.info.height);
        assert.ok(maxDiff(got.data, want.data) <= TOLERANCE, `max diff ${maxDiff(got.data, want.data)}`);
    });

    test(`${name} reaches the model as the same tensor as the upright image`, async () => {
        const ocr = await stubOcr();
        const want = await ocr.preprocess(path.join(FIXTURES, 'upright.png'));
        const got = await ocr.preprocess(path.join(FIXTURES, name));
        assert.ok(maxDiff(got.data, want.data) <= TOLERANCE / 127.5);
    });
}

test('a sharp instance the caller built is not re-oriented', () => {
    const img = sharp(path.join(FIXTURES, 'orient-6.jpg'));
    assert.equal(openImage(img), img);
});

test('without auto-orient the fixture is not upright (guards the fixture)', async () => {
    const raw = await grey(sharp(path.join(FIXTURES, 'orient-6.jpg')));
    assert.equal(raw.info.width, 32);
});

test('transparency is composited onto white', async () => {
    const want = await grey(sharp(path.join(FIXTURES, 'alpha-text.expected.png')));
    const got = await loadedPage(path.join(FIXTURES, 'alpha-text.png'));
    assert.equal(got.info.channels, 1);
    assert.equal(got.data[0], 255);
    assert.ok(maxDiff(got.data, want.data) <= 1, `max diff ${maxDiff(got.data, want.data)}`);
});

test('a transparent line reaches the model as dark on white', async () => {
    const ocr = await stubOcr();
    const want = await ocr.preprocess(path.join(FIXTURES, 'alpha-text.expected.png'));
    const got = await ocr.preprocess(path.join(FIXTURES, 'alpha-text.png'));
    assert.ok(maxDiff(got.data, want.data) <= 1.5 / 127.5);
});

test('without flattening the background is black (guards the fixture)', async () => {
    const naive = await grey(sharp(path.join(FIXTURES, 'alpha-text.png')));
    assert.equal(naive.data[0], 0);
});

// The old page path was `sharp(file).grayscale()`, and the old line path the
// same, so both are compared against it.
const OPAQUE = SAMPLES.concat(['upright.png', 'alpha-opaque.png', 'orient-1.jpg']
    .map((f) => path.join(FIXTURES, f)));
for (const file of OPAQUE) {
    test(`${path.basename(file)}: opaque untagged input is byte-identical to the old path`, async () => {
        const old = await grey(sharp(file));
        const now = await grey(openImage(file).flatten({ background: '#ffffff' }));
        assert.equal(now.info.channels, old.info.channels);
        assert.ok(Buffer.compare(now.data, old.data) === 0);

        const oldPage = await grey(sharp(await sharp(old.data, {
            raw: { width: old.info.width, height: old.info.height, channels: 1 },
        }).png().toBuffer()));
        const page = await loadedPage(file);
        // The page path also corrects polarity; these inputs are all dark on
        // light, so the probe leaves them alone and the bytes must match.
        assert.ok(Buffer.compare(page.data, oldPage.data) === 0);

        const ocr = await stubOcr();
        const tensor = await ocr.preprocess(file);
        const oldTensor = await ocr.preprocess(sharp(file));
        assert.deepEqual(Array.from(tensor.data), Array.from(oldTensor.data));
    });
}

test('opaque RGBA is not altered by flattening', async () => {
    const a = await loadedPage(path.join(FIXTURES, 'alpha-opaque.png'));
    const b = await loadedPage(path.join(FIXTURES, 'upright.png'));
    assert.ok(Buffer.compare(a.data, b.data) === 0);
});

// LineSegmenter.segment also decodes a path or Buffer itself, so it reads the
// same way. A page of blobs, as in line-profile.test.js, so rule suppression
// leaves it alone.
async function blobPage() {
    const W = 600, H = 200;
    const g = new Uint8Array(W * H).fill(255);
    for (const top of [30, 110]) {
        for (let y = top; y < top + 40; y++)
            for (let k = 0; k < 20; k++)
                for (let i = 0; i < 14; i++) g[y * W + 60 + k * 24 + i] = 0;
    }
    return { W, H, g };
}

async function linesOf(source) {
    const LineSegmenter = require('../src/segmenter');
    const lines = await new LineSegmenter().segment(source);
    return Promise.all(lines.map(async (l) => ({
        bbox: l.bbox,
        px: (await l.img.grayscale().raw().toBuffer()).toString('base64'),
    })));
}

test('LineSegmenter.segment reads an EXIF-rotated page upright', async () => {
    const { W, H, g } = await blobPage();
    const upright = await sharp(Buffer.from(g), { raw: { width: W, height: H, channels: 1 } }).png().toBuffer();
    const stored = await sharp(upright).rotate(-90).png().toBuffer();
    const tagged = await sharp(stored).withMetadata({ orientation: 6 }).png().toBuffer();
    const want = await linesOf(upright);
    assert.equal(want.length, 2);
    assert.deepEqual(await linesOf(tagged), want);
});

test('LineSegmenter.segment reads a transparent page as dark on white', async () => {
    const { W, H, g } = await blobPage();
    const rgba = Buffer.alloc(W * H * 4); // (0, 0, 0, 0) everywhere
    for (let i = 0; i < g.length; i++) if (g[i] === 0) rgba[i * 4 + 3] = 255; // opaque black ink
    const transparent = await sharp(rgba, { raw: { width: W, height: H, channels: 4 } }).png().toBuffer();
    const opaque = await sharp(Buffer.from(g), { raw: { width: W, height: H, channels: 1 } }).png().toBuffer();
    const want = await linesOf(opaque);
    assert.equal(want.length, 2);
    assert.deepEqual((await linesOf(transparent)).map((l) => l.bbox), want.map((l) => l.bbox));
});
