package imageio

import (
	"bytes"
	"encoding/binary"
	"image"
	"image/color"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"testing"
)

// Images are read as they are displayed: EXIF orientation applied, transparency
// composited onto white. Inputs that are already upright and opaque take the
// same path as before, byte for byte.
//
// The fixtures are shared by all four bindings and generated by
// scripts/generate_input_fixtures.py; its docstring describes each one.

var fixtures = filepath.Join("..", "..", "..", "data", "fixtures", "input")

var oriented = []string{
	"orient-1.jpg", "orient-2.jpg", "orient-3.jpg", "orient-4.jpg",
	"orient-5.jpg", "orient-6.jpg", "orient-7.jpg", "orient-8.jpg",
	"orient-6-be.jpg", "orient-6.png",
}

// JPEG rounding on these block-aligned quality-100 fixtures is a few levels at
// most; a wrong orientation differs by 36 or more on average, or changes shape.
const orientTolerance = 8

func decodeFile(t *testing.T, path string) image.Image {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	img, _, err := image.Decode(bytes.NewReader(data))
	if err != nil {
		t.Fatal(err)
	}
	return img
}

func loadFile(t *testing.T, path string) image.Image {
	t.Helper()
	img, err := Load(path)
	if err != nil {
		t.Fatal(err)
	}
	return img
}

func greyPixels(img image.Image) (int, int, []uint8) {
	b := img.Bounds()
	out := make([]uint8, 0, b.Dx()*b.Dy())
	for y := b.Min.Y; y < b.Max.Y; y++ {
		for x := b.Min.X; x < b.Max.X; x++ {
			out = append(out, color.GrayModel.Convert(img.At(x, y)).(color.Gray).Y)
		}
	}
	return b.Dx(), b.Dy(), out
}

func maxAbsDiff(a, b []uint8) int {
	m := 0
	for i := range a {
		d := int(a[i]) - int(b[i])
		if d < 0 {
			d = -d
		}
		if d > m {
			m = d
		}
	}
	return m
}

func TestEveryExifOrientationLoadsUpright(t *testing.T) {
	uw, uh, up := greyPixels(decodeFile(t, filepath.Join(fixtures, "upright.png")))
	for _, name := range oriented {
		t.Run(name, func(t *testing.T) {
			w, h, got := greyPixels(loadFile(t, filepath.Join(fixtures, name)))
			if w != uw || h != uh {
				t.Fatalf("loaded %dx%d, want %dx%d", w, h, uw, uh)
			}
			if d := maxAbsDiff(got, up); d > orientTolerance {
				t.Fatalf("max pixel difference %d from the upright image", d)
			}
		})
	}
}

// Guards the fixtures: decoding without the tag must give a different picture.
func TestTheFixturesAreNotUprightWithoutTheTag(t *testing.T) {
	uw, uh, up := greyPixels(decodeFile(t, filepath.Join(fixtures, "upright.png")))
	for _, name := range oriented[1:] {
		w, h, raw := greyPixels(decodeFile(t, filepath.Join(fixtures, name)))
		if w == uw && h == uh && maxAbsDiff(raw, up) <= orientTolerance {
			t.Errorf("%s decodes upright without its tag; it cannot test orientation", name)
		}
	}
}

func TestExifOrientationReadsEachTagAndByteOrder(t *testing.T) {
	want := map[string]int{"orient-6-be.jpg": 6, "orient-6.png": 6, "upright.png": 1, "alpha-text.png": 1}
	for n := 1; n <= 8; n++ {
		want["orient-"+string(rune('0'+n))+".jpg"] = n
	}
	for name, tag := range want {
		data, err := os.ReadFile(filepath.Join(fixtures, name))
		if err != nil {
			t.Fatal(err)
		}
		if got := ExifOrientation(data); got != tag {
			t.Errorf("%s: orientation %d, want %d", name, got, tag)
		}
	}
}

// A malformed or truncated header is read as "no tag", never as a panic: the
// file decoded before this parser existed and must still decode.
func TestExifOrientationToleratesGarbage(t *testing.T) {
	data, err := os.ReadFile(filepath.Join(fixtures, "orient-6.jpg"))
	if err != nil {
		t.Fatal(err)
	}
	for n := 0; n < len(data) && n < 200; n++ {
		ExifOrientation(data[:n])
	}
	for _, b := range [][]byte{nil, {0xFF}, {0xFF, 0xD8, 0xFF, 0xE1, 0xFF, 0xFF}, []byte("\x89PNG\r\n\x1a\n\xff\xff\xff\xff")} {
		if got := ExifOrientation(b); got != 1 {
			t.Errorf("garbage %x: orientation %d, want 1", b, got)
		}
	}
}

func TestTransparencyIsCompositedOntoWhite(t *testing.T) {
	_, _, want := greyPixels(decodeFile(t, filepath.Join(fixtures, "alpha-text.expected.png")))
	_, _, got := greyPixels(FlattenOnWhite(loadFile(t, filepath.Join(fixtures, "alpha-text.png"))))
	if got[0] != 255 {
		t.Fatalf("transparent background reads as %d, want 255", got[0])
	}
	if d := maxAbsDiff(got, want); d > 1 {
		t.Fatalf("max difference %d from the expected composite", d)
	}
}

// Guards the fixture: the conversion the fix replaces turns the background black.
func TestWithoutFlatteningTheBackgroundIsBlack(t *testing.T) {
	_, _, naive := greyPixels(decodeFile(t, filepath.Join(fixtures, "alpha-text.png")))
	if naive[0] != 0 {
		t.Fatalf("naive background %d, want 0", naive[0])
	}
}

func opaqueInputs(t *testing.T) []string {
	samples, err := filepath.Glob(filepath.Join("..", "..", "..", "data", "images", "*"))
	if err != nil || len(samples) == 0 {
		t.Fatalf("no sample images: %v", err)
	}
	sort.Strings(samples)
	for _, f := range []string{"upright.png", "alpha-opaque.png", "orient-1.jpg"} {
		samples = append(samples, filepath.Join(fixtures, f))
	}
	return samples
}

// The old path was image.Decode and then the image as decoded. For an opaque,
// untagged input Load returns exactly that, and FlattenOnWhite returns it
// unchanged, so preprocessing sees the same value it always did.
func TestOpaqueUntaggedInputIsUnchanged(t *testing.T) {
	for _, path := range opaqueInputs(t) {
		old := decodeFile(t, path)
		now := loadFile(t, path)
		if !reflect.DeepEqual(now, old) {
			t.Errorf("%s: Load differs from image.Decode", filepath.Base(path))
		}
		if flat := FlattenOnWhite(now); !reflect.DeepEqual(flat, now) {
			t.Errorf("%s: FlattenOnWhite altered an opaque image", filepath.Base(path))
		}
	}
}

func TestOpaqueRGBAIsNotAlteredByFlattening(t *testing.T) {
	_, _, a := greyPixels(FlattenOnWhite(loadFile(t, filepath.Join(fixtures, "alpha-opaque.png"))))
	_, _, b := greyPixels(decodeFile(t, filepath.Join(fixtures, "upright.png")))
	if !bytes.Equal(a, b) {
		t.Fatal("an RGBA image with alpha 255 everywhere changed when flattened")
	}
}

// tiff builds a minimal TIFF header with one IFD0 entry for tag 0x0112.
func tiff(bigEndian bool, typ uint16, value uint32) []byte {
	var bo binary.ByteOrder = binary.LittleEndian
	head := []byte("II")
	if bigEndian {
		bo, head = binary.BigEndian, []byte("MM")
	}
	b := make([]byte, 8+2+12+4)
	copy(b, head)
	bo.PutUint16(b[2:], 42)
	bo.PutUint32(b[4:], 8)
	bo.PutUint16(b[8:], 1)
	bo.PutUint16(b[10:], 0x0112)
	bo.PutUint16(b[12:], typ)
	bo.PutUint32(b[14:], 1)
	if typ == 3 {
		bo.PutUint16(b[18:], uint16(value))
	} else {
		bo.PutUint32(b[18:], value)
	}
	return b
}

func TestTiffOrientationAcceptsShortAndLong(t *testing.T) {
	for _, big := range []bool{false, true} {
		if got := tiffOrientation(tiff(big, 3, 6)); got != 6 {
			t.Errorf("SHORT, big-endian %v: %d, want 6", big, got)
		}
		if got := tiffOrientation(tiff(big, 4, 8)); got != 8 {
			t.Errorf("LONG, big-endian %v: %d, want 8", big, got)
		}
		if got := tiffOrientation(tiff(big, 4, 1<<31)); got != 0 {
			t.Errorf("LONG out of range, big-endian %v: %d, want 0", big, got)
		}
		if got := tiffOrientation(tiff(big, 7, 6)); got != 0 {
			t.Errorf("UNDEFINED type, big-endian %v: %d, want 0", big, got)
		}
	}
	// An IFD offset near 2^32 must be refused, not wrapped.
	b := tiff(false, 3, 6)
	binary.LittleEndian.PutUint32(b[4:], 0xFFFFFFFE)
	if got := tiffOrientation(b); got != 0 {
		t.Errorf("huge IFD offset: %d, want 0", got)
	}
	// An IFD offset inside the header is refused.
	binary.LittleEndian.PutUint32(b[4:], 2)
	if got := tiffOrientation(b); got != 0 {
		t.Errorf("IFD offset inside the header: %d, want 0", got)
	}
}

// The walk has to step over fill bytes and an APP1 that is not Exif (XMP is
// the common one) to reach the Exif segment behind them.
func TestJpegExifSkipsFillBytesAndOtherAPP1Segments(t *testing.T) {
	data, err := os.ReadFile(filepath.Join(fixtures, "orient-6.jpg"))
	if err != nil {
		t.Fatal(err)
	}
	xmp := append([]byte("http://ns.adobe.com/xap/1.0/\x00"), []byte("<x:xmpmeta/>")...)
	seg := []byte{0xFF, 0xE1, 0, 0}
	binary.BigEndian.PutUint16(seg[2:], uint16(len(xmp)+2))
	seg = append(seg, xmp...)
	var b []byte
	b = append(b, data[:2]...)      // SOI
	b = append(b, 0xFF, 0xFF, 0xFF) // fill bytes before the next marker
	b = append(b, seg[1:]...)       // the fill run ends with this marker's FF
	b = append(b, data[2:]...)
	if got := ExifOrientation(b); got != 6 {
		t.Fatalf("orientation %d, want 6", got)
	}
}

// pngWithChunk builds a PNG signature followed by one chunk whose length field says
// declared, carrying payload, and an IEND. The CRCs are zero; the tag reader
// does not check them.
func pngWithChunk(typ string, declared uint32, payload []byte) []byte {
	b := []byte("\x89PNG\r\n\x1a\n")
	b = binary.BigEndian.AppendUint32(b, declared)
	b = append(b, typ...)
	b = append(b, payload...)
	b = append(b, 0, 0, 0, 0)
	b = binary.BigEndian.AppendUint32(b, 0)
	b = append(b, "IEND"...)
	return append(b, 0, 0, 0, 0)
}

// jpegWithExif builds SOI, one APP1 Exif segment holding t, and EOI.
func jpegWithExif(t []byte) []byte {
	b := []byte{0xFF, 0xD8, 0xFF, 0xE1}
	b = binary.BigEndian.AppendUint16(b, uint16(2+6+len(t)))
	b = append(b, "Exif\x00\x00"...)
	b = append(b, t...)
	return append(b, 0xFF, 0xD9)
}

// A chunk length that runs past the end of the file is read as "no tag". The
// slice it would take is out of range, so without the bound this panics.
func TestAnOversizedPNGChunkLengthIsNoTag(t *testing.T) {
	payload := tiff(false, 3, 6)
	// The smallest length that overruns: everything after the chunk header
	// and its CRC, plus one.
	over := uint32(len(pngWithChunk("eXIf", 0, payload)) - 8 - 12 + 1)
	for _, declared := range []uint32{over, 1 << 20, 0x7FFFFFFF, 0xFFFFFFFF} {
		for _, typ := range []string{"eXIf", "tEXt"} {
			if got := ExifOrientation(pngWithChunk(typ, declared, payload)); got != 1 {
				t.Errorf("%s length %d: orientation %d, want 1", typ, declared, got)
			}
		}
	}
	// The same chunk with its true length is read, so the cases above are
	// refused for their length alone.
	if got := ExifOrientation(pngWithChunk("eXIf", uint32(len(payload)), payload)); got != 6 {
		t.Fatalf("well-formed eXIf: orientation %d, want 6", got)
	}
}

// An IFD offset past the end of the TIFF structure is read as "no tag", in both
// containers. Reading the entry count there is out of range, so without the
// bound this panics.
func TestAnIFDOffsetBeyondTheBufferIsNoTag(t *testing.T) {
	good := tiff(false, 3, 6)
	for _, off := range []uint32{uint32(len(good)) - 1, uint32(len(good)), uint32(len(good)) + 64, 1 << 20, 0xFFFFFFFE} {
		b := append([]byte(nil), good...)
		binary.LittleEndian.PutUint32(b[4:], off)
		if got := tiffOrientation(b); got != 0 {
			t.Errorf("IFD offset %d: tiffOrientation %d, want 0", off, got)
		}
		for name, file := range map[string][]byte{
			"JPEG": jpegWithExif(b),
			"PNG":  pngWithChunk("eXIf", uint32(len(b)), b),
		} {
			if got := ExifOrientation(file); got != 1 {
				t.Errorf("%s, IFD offset %d: orientation %d, want 1", name, off, got)
			}
		}
	}
	for name, file := range map[string][]byte{
		"JPEG": jpegWithExif(good),
		"PNG":  pngWithChunk("eXIf", uint32(len(good)), good),
	} {
		if got := ExifOrientation(file); got != 6 {
			t.Fatalf("well-formed %s: orientation %d, want 6", name, got)
		}
	}
}
