package imageio

import (
	"bytes"
	"image"
	"image/color"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"testing"
)

// Images are read as they are displayed: EXIF orientation applied, transparency
// composited onto white. Inputs that are already upright and opaque take the
// same path as before, byte for byte.
//
// The fixtures are shared by all four bindings and generated by
// scripts/generate_input_fixtures.py; its docstring describes each one.

var fixtures = filepath.Join("..", "..", "..", "data", "fixtures", "input")

var oriented = []string{
	"orient-1.jpg", "orient-2.jpg", "orient-3.jpg", "orient-4.jpg",
	"orient-5.jpg", "orient-6.jpg", "orient-7.jpg", "orient-8.jpg",
	"orient-6-be.jpg", "orient-6.png",
}

// JPEG rounding on these block-aligned quality-100 fixtures is a few levels at
// most; a wrong orientation differs by 36 or more on average, or changes shape.
const orientTolerance = 8

func decodeFile(t *testing.T, path string) image.Image {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	img, _, err := image.Decode(bytes.NewReader(data))
	if err != nil {
		t.Fatal(err)
	}
	return img
}

func loadFile(t *testing.T, path string) image.Image {
	t.Helper()
	img, err := Load(path)
	if err != nil {
		t.Fatal(err)
	}
	return img
}

func greyPixels(img image.Image) (int, int, []uint8) {
	b := img.Bounds()
	out := make([]uint8, 0, b.Dx()*b.Dy())
	for y := b.Min.Y; y < b.Max.Y; y++ {
		for x := b.Min.X; x < b.Max.X; x++ {
			out = append(out, color.GrayModel.Convert(img.At(x, y)).(color.Gray).Y)
		}
	}
	return b.Dx(), b.Dy(), out
}

func maxAbsDiff(a, b []uint8) int {
	m := 0
	for i := range a {
		d := int(a[i]) - int(b[i])
		if d < 0 {
			d = -d
		}
		if d > m {
			m = d
		}
	}
	return m
}

func TestEveryExifOrientationLoadsUpright(t *testing.T) {
	uw, uh, up := greyPixels(decodeFile(t, filepath.Join(fixtures, "upright.png")))
	for _, name := range oriented {
		t.Run(name, func(t *testing.T) {
			w, h, got := greyPixels(loadFile(t, filepath.Join(fixtures, name)))
			if w != uw || h != uh {
				t.Fatalf("loaded %dx%d, want %dx%d", w, h, uw, uh)
			}
			if d := maxAbsDiff(got, up); d > orientTolerance {
				t.Fatalf("max pixel difference %d from the upright image", d)
			}
		})
	}
}

// Guards the fixtures: decoding without the tag must give a different picture.
func TestTheFixturesAreNotUprightWithoutTheTag(t *testing.T) {
	uw, uh, up := greyPixels(decodeFile(t, filepath.Join(fixtures, "upright.png")))
	for _, name := range oriented[1:] {
		w, h, raw := greyPixels(decodeFile(t, filepath.Join(fixtures, name)))
		if w == uw && h == uh && maxAbsDiff(raw, up) <= orientTolerance {
			t.Errorf("%s decodes upright without its tag; it cannot test orientation", name)
		}
	}
}

func TestExifOrientationReadsEachTagAndByteOrder(t *testing.T) {
	want := map[string]int{"orient-6-be.jpg": 6, "orient-6.png": 6, "upright.png": 1, "alpha-text.png": 1}
	for n := 1; n <= 8; n++ {
		want["orient-"+string(rune('0'+n))+".jpg"] = n
	}
	for name, tag := range want {
		data, err := os.ReadFile(filepath.Join(fixtures, name))
		if err != nil {
			t.Fatal(err)
		}
		if got := ExifOrientation(data); got != tag {
			t.Errorf("%s: orientation %d, want %d", name, got, tag)
		}
	}
}

// A malformed or truncated header is read as "no tag", never as a panic: the
// file decoded before this parser existed and must still decode.
func TestExifOrientationToleratesGarbage(t *testing.T) {
	data, err := os.ReadFile(filepath.Join(fixtures, "orient-6.jpg"))
	if err != nil {
		t.Fatal(err)
	}
	for n := 0; n < len(data) && n < 200; n++ {
		ExifOrientation(data[:n])
	}
	for _, b := range [][]byte{nil, {0xFF}, {0xFF, 0xD8, 0xFF, 0xE1, 0xFF, 0xFF}, []byte("\x89PNG\r\n\x1a\n\xff\xff\xff\xff")} {
		if got := ExifOrientation(b); got != 1 {
			t.Errorf("garbage %x: orientation %d, want 1", b, got)
		}
	}
}

func TestTransparencyIsCompositedOntoWhite(t *testing.T) {
	_, _, want := greyPixels(decodeFile(t, filepath.Join(fixtures, "alpha-text.expected.png")))
	_, _, got := greyPixels(FlattenOnWhite(loadFile(t, filepath.Join(fixtures, "alpha-text.png"))))
	if got[0] != 255 {
		t.Fatalf("transparent background reads as %d, want 255", got[0])
	}
	if d := maxAbsDiff(got, want); d > 1 {
		t.Fatalf("max difference %d from the expected composite", d)
	}
}

// Guards the fixture: the conversion the fix replaces turns the background black.
func TestWithoutFlatteningTheBackgroundIsBlack(t *testing.T) {
	_, _, naive := greyPixels(decodeFile(t, filepath.Join(fixtures, "alpha-text.png")))
	if naive[0] != 0 {
		t.Fatalf("naive background %d, want 0", naive[0])
	}
}

func opaqueInputs(t *testing.T) []string {
	samples, err := filepath.Glob(filepath.Join("..", "..", "..", "data", "images", "*"))
	if err != nil || len(samples) == 0 {
		t.Fatalf("no sample images: %v", err)
	}
	sort.Strings(samples)
	for _, f := range []string{"upright.png", "alpha-opaque.png", "orient-1.jpg"} {
		samples = append(samples, filepath.Join(fixtures, f))
	}
	return samples
}

// The old path was image.Decode and then the image as decoded. For an opaque,
// untagged input Load returns exactly that, and FlattenOnWhite returns it
// unchanged, so preprocessing sees the same value it always did.
func TestOpaqueUntaggedInputIsUnchanged(t *testing.T) {
	for _, path := range opaqueInputs(t) {
		old := decodeFile(t, path)
		now := loadFile(t, path)
		if !reflect.DeepEqual(now, old) {
			t.Errorf("%s: Load differs from image.Decode", filepath.Base(path))
		}
		if flat := FlattenOnWhite(now); !reflect.DeepEqual(flat, now) {
			t.Errorf("%s: FlattenOnWhite altered an opaque image", filepath.Base(path))
		}
	}
}

func TestOpaqueRGBAIsNotAlteredByFlattening(t *testing.T) {
	_, _, a := greyPixels(FlattenOnWhite(loadFile(t, filepath.Join(fixtures, "alpha-opaque.png"))))
	_, _, b := greyPixels(decodeFile(t, filepath.Join(fixtures, "upright.png")))
	if !bytes.Equal(a, b) {
		t.Fatal("an RGBA image with alpha 255 everywhere changed when flattened")
	}
}
