"""
Images are read as they are displayed: EXIF orientation applied, transparency
composited onto white. Inputs that are already upright and opaque take the
same path as before, byte for byte.

The fixtures are shared by all four bindings and generated by
``scripts/generate_input_fixtures.py``; its docstring describes each one.
"""

from pathlib import Path

import numpy as np
import pytest
from PIL import Image

from monocr_onnx.predictor import load_image, to_grey

REPO = Path(__file__).resolve().parents[2]
FIXTURES = REPO / "data" / "fixtures" / "input"
SAMPLES = sorted((REPO / "data" / "images").iterdir())

ORIENTED = [f"orient-{n}.jpg" for n in range(1, 9)] + ["orient-6-be.jpg", "orient-6.png"]

# JPEG rounding on these block-aligned quality-100 fixtures is 0 with Pillow;
# a wrong orientation differs by 36 or more on average, or changes the shape.
TOLERANCE = 8


def _grey(path):
    return np.asarray(to_grey(load_image(path)), dtype=np.int16)


def _upright():
    return np.asarray(Image.open(FIXTURES / "upright.png"), dtype=np.int16)


@pytest.mark.parametrize("name", ORIENTED)
def test_every_exif_orientation_loads_upright(name):
    got = _grey(FIXTURES / name)
    ref = _upright()
    assert got.shape == ref.shape
    assert int(np.abs(got - ref).max()) <= TOLERANCE


@pytest.mark.parametrize("name", [n for n in ORIENTED if n != "orient-1.jpg"])
def test_the_fixture_is_not_upright_without_the_tag(name):
    """Guards the fixture: ignoring the tag must give a different picture."""
    raw = np.asarray(Image.open(FIXTURES / name).convert("L"), dtype=np.int16)
    ref = _upright()
    assert raw.shape != ref.shape or np.abs(raw - ref).mean() > 20


@pytest.mark.parametrize("name", ORIENTED)
def test_the_model_input_is_the_same_for_every_orientation(make_ocr, name):
    ocr = make_ocr()
    ocr.predict_line(FIXTURES / "upright.png")
    want = ocr.fake_session.last_input
    ocr.predict_line(FIXTURES / name)
    got = ocr.fake_session.last_input
    assert got.shape == want.shape
    assert float(np.abs(got - want).max()) <= TOLERANCE / 127.5


def test_a_decoded_image_is_not_reoriented():
    """The caller owns the orientation of an Image it already decoded."""
    img = Image.open(FIXTURES / "orient-6.jpg")
    assert load_image(img) is img


def test_transparency_is_composited_onto_white():
    got = np.asarray(to_grey(load_image(FIXTURES / "alpha-text.png")), dtype=np.int16)
    want = np.asarray(Image.open(FIXTURES / "alpha-text.expected.png"), dtype=np.int16)
    assert got.shape == want.shape
    assert got[0, 0] == 255  # (0, 0, 0, 0) background reads as white
    assert int(np.abs(got - want).max()) <= 1


def test_without_compositing_the_background_is_black():
    """Guards the fixture: the naive conversion is what the fix replaces."""
    naive = np.asarray(Image.open(FIXTURES / "alpha-text.png").convert("L"))
    assert naive[0, 0] == 0


def test_a_transparent_line_reaches_the_model_as_dark_on_white(make_ocr):
    ocr = make_ocr()
    ocr.predict_line(FIXTURES / "alpha-text.expected.png")
    want = ocr.fake_session.last_input
    ocr.predict_line(FIXTURES / "alpha-text.png")
    got = ocr.fake_session.last_input
    assert float(np.abs(got - want).max()) <= 1.5 / 127.5


@pytest.mark.parametrize(
    "path",
    SAMPLES + [FIXTURES / "upright.png", FIXTURES / "alpha-opaque.png", FIXTURES / "orient-1.jpg"],
    ids=lambda p: p.name,
)
def test_opaque_untagged_input_is_byte_identical_to_the_old_path(path):
    """The old path was ``Image.open(p)`` then ``.convert("L")``."""
    old = Image.open(path)
    old = old if old.mode == "L" else old.convert("L")
    assert to_grey(load_image(path)).tobytes() == old.tobytes()


def test_opaque_rgba_is_not_altered_by_compositing():
    a = to_grey(load_image(FIXTURES / "alpha-opaque.png"))
    b = Image.open(FIXTURES / "upright.png")
    assert a.tobytes() == b.tobytes()


def _blob_page(transparent):
    """Two lines of blobs; as RGBA on (0, 0, 0, 0) when `transparent`."""
    a = np.full((200, 600), 255, dtype=np.uint8)
    for top in (30, 110):
        for k in range(20):
            a[top : top + 40, 60 + k * 24 : 74 + k * 24] = 0
    if not transparent:
        return Image.fromarray(a, mode="L")
    rgba = np.zeros((200, 600, 4), dtype=np.uint8)
    rgba[..., 3] = np.where(a == 0, 255, 0)
    return Image.fromarray(rgba, mode="RGBA")


def test_the_segmenter_reads_a_transparent_page_as_dark_on_white():
    from monocr_onnx.segmenter import LineSegmenter

    seg = LineSegmenter()
    want = [line["bbox"] for line in seg.segment(_blob_page(False))]
    assert len(want) == 2
    assert [line["bbox"] for line in seg.segment(_blob_page(True))] == want


@pytest.mark.parametrize(
    "name,reference",
    [("orient-6.jpg", "upright.png"), ("orient-8.jpg", "upright.png"),
     ("alpha-text.png", "alpha-text.expected.png")],
)
def test_the_page_path_reads_files_as_displayed(make_ocr, name, reference):
    """``predict_page`` opens the file itself, so it orients and flattens too."""
    ocr = make_ocr()
    ocr.predict_page(FIXTURES / reference)
    want = ocr.fake_session.last_input
    ocr.predict_page(FIXTURES / name)
    got = ocr.fake_session.last_input
    assert got.shape == want.shape
    assert float(np.abs(got - want).max()) <= TOLERANCE / 127.5
